name: 🏷️ Auto Label & Assign

on:
  pull_request:
    types: [opened, synchronize]
  issues:
    types: [opened]

jobs:
  label:
    name: 🏷️ Auto Label
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      issues: write

    steps:
      - uses: actions/labeler@v5
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          sync-labels: true
